version: "0.2"

env:
  shell: bash

phases:
  install:
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - source $HOME/.cargo/env
  build:
    commands:
      - cargo clean
artifacts:
  files:
    - templates/*
    - src/*
  discard-paths: "no"
cache:
  paths:
    - $HOME/.cargo/registry/**/*
